apiVersion: batch/v1
kind: CronJob
metadata:
  name: semogong-dash
spec:
  schedule: "0 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: semogong-dash
            image: wjdqlsdlsp/make_plot:latest
            envFrom:
            - configMapRef:
                name: config-dev
          restartPolicy: OnFailure